apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server
  namespace: dev  
  labels:
   app: frontend-nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend-nginx
template:
  metadata:
    labels:
      app: frontend-nginx
spec:
  containers:
    - name: frontend-nginx
      image: nginx:registry.gitlab.com/malo2004/k8s-app:1.0.0
      ports:
        - containerPort: 80
