apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-server
  namespace: dev  
  labels:
   app: frontend-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-server
  template:
   metadata:
    labels:
      app: frontend-server
   spec:
     imagePullSecrets:
       - name: regcred
     containers:
        - name: frontend-server
          image: ghcr.io/malo2004/k8s-app:1.0.1
          ports:
           - containerPort: 80
