apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: dev
  labels:
   run: frontend-nginx
spec:
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 30102
  type: NodePort
  selector:
    app: frontend-nginx
